### PR TITLE
feat(contrast): add contrast blurb

### PR DESCRIPTION
**Pull request by tavogel**
## Overview

DO NOT MERGE (still negotiating contract)

Why/What/How of Contrast Security

---

#### Meta

- [x] provide a descriptive topic
- [x] provide an overview of contribution
- [x] no sensitive content included, such as:
  - security & privacy policy violating content
  - content considered competitive intelligence
  - keys, tokens or credentials
- [x] documentation format follows [this template][template]
- [x] fork is up to date ([see this guide from github](https://help.github.com/articles/syncing-a-fork/))
- [ ] "work in progress" commits are squashed ([see "Squashing Commits"](https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History))
- [x] commits follow the [Karma][karma-format] or [Commitizen](https://www.npmjs.com/package/commitizen) format

[template]: ../.template.md
[karma-format]: https://karma-runner.github.io/1.0/dev/git-commit-msg.html

### CODE REVIEW

**Comment by ruxandrafed** [comment]
Updates: we just finalized negotiating our contract with Contrast yesterday (as per @csawatz). A new security prime for rolling this out will be named soon. Until then, I've asked @ian-stackaspect-telus and @isand3r to review Tom's docs and see if there's anything to add/update.

**Comment by tavogel** [comment]
Noooooo~~~~~oooooo~~~~~

**Comment by isand3r** [comment]
Updated the blurb and added a link to the setup guide.

**Comment by isand3r** [comment]
Good thought @ruxandrafed, I'll add a link back to the RA doc

**Pull request merged**
