### PR TITLE
refactor(svg-logo): clean up and add comments

### PR DESCRIPTION
**Pull request by wascloud**
## Overview

Optimize SVG Source:
- changed vertical spacer to `<line>` instead of `<text>`
- remove unnecessary metadata (inkscape/sodipodi)
- add comments/ids for easier modification (eg. `TELUS-Letter-T` vs. `polyline242`)
- add system font stack for better cross-platform rendering

Optimize SVG Compressed:
- Compressed using SVGO

### Details
screen shot 2018-09-11 at 4 53 49 pm
(top = before / bottom = after)

#### Meta

> Please read and confirm each of the following:

- [ ] this topic was discussed in the [Technology Forum][technology-forum] _(ignore if the pull request represents small changes)_
- [ ] provided a descriptive topic and overview of contribution
- [ ] documentation format follows the [topic template][template]
- [ ] fork is up to date _(Hint: ["Syncing a Fork"][guide-forks])_
- [ ] "work in progress" commits are squashed _(Hint: ["Squashing Commits"][guide-squash])_
- [ ] commits follow the [Conventional ChangeLog][conventional-changelog] format
- [ ] no sensitive content included, such as:
  - content considered competitive intelligence
  - security & privacy policy violating content
  - keys, tokens or credentials

[template]: https://github.com/telus/reference-architecture/blob/master/.template.md
[conventional-changelog]: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular
[guide-forks]: https://help.github.com/articles/syncing-a-fork/
[guide-squash]: https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History
[technology-forum]: https://github.com/telus/technology-forum]

### CODE REVIEW

**Comment by ahmadnassri** [comment]
@wascloud the source file had `<text>` on purpose so it's editable and for re-use in other repos too

the output file was already optimized with `svgo`

if you keep the text and make your changes for the line in accordance to the format, we can merge.

**Comment by wascloud** [comment]
@ahmadnassri `<text>` is still there! Check line 72:

screen shot 2018-09-11 at 10 46 02 pm

**Comment by ahmadnassri** [comment]
ah, then I was confused by your description, and the preview on mobile didn't do it justice, I'll take another look today. thanks!

**Comment by ruxandrafed** [comment]
@wascloud Wasim, can you please review the latest comments and make the changes so we can merge this PR? :) Thank you!

**Comment by wascloud** [comment]
@kspaans @ruxandrafed -- Just closing off the PR. I merged the latest master, and I double checked the preview on the GitHub UI (attached image). Since it's an image that autoscales, the "e" won't be cut off :). The new SVG is more on-brand 👍 

screen shot 2019-02-14 at 4 07 02 pm

**Pull request closed without merging**
