### PR TITLE
docs: remove references to BFF

### PR DESCRIPTION
**Pull request by ruxandrafed**
**DO NOT MERGE** until https://github.com/telus/telus-isomorphic-starter-kit/pull/326 is merged.

## Overview

Remove/update references to `BFF` in all relevant docs.
Forum Issue [#227 merge UI / BFF Containers](https://github.com/telus/technology-forum/issues/227)

---

#### Meta

> Please read and confirm each of the following:

- [x] this topic was discussed in the [Technology Forum][technology-forum] _(ignore if the pull request represents small changes)_
- [x] provided a descriptive topic and overview of contribution
- [x] documentation format follows the [topic template][template]
- [x] fork is up to date _(Hint: ["Syncing a Fork"][guide-forks])_
- [x] "work in progress" commits are squashed _(Hint: ["Squashing Commits"][guide-squash])_
- [x] commits follow the [Conventional ChangeLog][conventional-changelog] format
- [x] no sensitive content included, such as:
  - content considered competitive intelligence
  - security & privacy policy violating content
  - keys, tokens or credentials

[template]: https://github.com/telus/reference-architecture/blob/master/.template.md
[conventional-changelog]: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular
[guide-forks]: https://help.github.com/articles/syncing-a-fork/
[guide-squash]: https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History
[technology-forum]: https://github.com/telus/technology-forum]

### CODE REVIEW

**Comment by ruxandrafed** [comment]
@tavogel Given we don't really use BFFs as they were intended, we've been discussing about slowly removing the term from our discussions and docs and just using the "backend" term. That's the rationale for my changes. But I guess that, yes, I could leave the BFF doc and just update it, but most people know what the purpose of a backend is and what should happen in there, etc.? 🤔

**Comment by tavogel** [comment]
I don't think it hurts to leave this. The documentation isn't wrong.

**Comment by zackiles** [comment]
For the most part, I agree with these changes. Original docs aren't wrong, but Rux's changes better reflect the change in #326 and are easier to reason about for a developer new to Digital.

**Comment by tavogel** [comment]
Keep in mind the BFF docs were removed from the starter kit as well. So essentially we have a BFF folder with no context. Unexplained acronyms are the worst, especially ones with double meanings. 

Maybe if we're rename the starter kit folder to just backend vs bff it makes more sense in the new context. Still feel like we should document when and where to use it though.

**Comment by ruxandrafed** [comment]
@tavogel This PR is one of my action items as part of https://github.com/telus/technology-forum/issues/227, which also includes cleaning up the term and renaming `bff` everywhere, so that we stay consistent ☺ My branch with the merge already has the folders, files, and docs updated accordingly: https://github.com/telus/telus-isomorphic-starter-kit/pull/326.

**Comment by tavogel** [comment]
Ok I see the /app/bff folder was named as /app/backend now. So I have no problems with this.

**Pull request merged**
