### PR TITLE
feat(seo): Update seo.md

### PR DESCRIPTION
**Pull request by danielcrough**
## Overview

Updating the page title standards.

#### Meta

> Please read and confirm each of the following:

- [ ] this topic was discussed in the [Technology Forum][technology-forum] _(ignore if the pull request represents small changes)_
- [ ] provided a descriptive topic and overview of contribution
- [ ] documentation format follows the [topic template][template]
- [ ] branch is up to date with master
- [ ] "work in progress" commits are squashed _(Hint: ["Squashing Commits"][guide-squash])_
- [ ] commits follow the [Conventional ChangeLog][conventional-changelog] format
- [ ] no sensitive content included, such as:
  - content considered competitive intelligence
  - security & privacy policy violating content
  - keys, tokens or credentials

[template]: https://github.com/telus/reference-architecture/blob/master/.template.md
[conventional-changelog]: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular
[guide-squash]: https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History
[technology-forum]: https://github.com/telus/technology-forum]

### CODE REVIEW

**Comment by danielcrough** [comment]
@maumercado can you help here? Not sure why this is blocked.

**Comment by danielcrough** [comment]
or @karlasamantha , sorry didn't see you were already looking at this.

**Comment by mattcan** [comment]
@danielcrough is this more along the lines of what you were looking to do? https://github.com/telus/reference-architecture/pull/235/files?short_path=d73fd48#diff-d73fd48c047b63fb6e7179797ae1fc17

**Comment by danielcrough** [comment]
@mattcan yes, thank you. Not sure what I did wrong but that looks right!

**Comment by mattcan** [comment]
You were creating a link in two different places. To be fair, it was done incorrectly before your change was added.

Here is how links work in Markdown: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

**Pull request merged**
