### PR TITLE
Create /Accessibilty/readme.md

### PR DESCRIPTION
**Pull request by owestinTelus**
## Overview

> Top-level accessibility page with links to current standards. 

**Forum Issue #** `telus/technology-forum#0`
> Link to the [Technology Forum][technology-forum] where this issue was discussed _(optional)_.

### Details

create new topic to replace outdate content under / development and /testing

---

#### Meta

> Please read and confirm each of the following:

- [ ] this topic was discussed in the [Technology Forum][technology-forum] _(ignore if the pull request represents small changes)_
- [ ] provided a descriptive topic and overview of contribution
- [ ] documentation format follows the [topic template][template]
- [ ] branch is up to date with master
- [ ] "work in progress" commits are squashed _(Hint: ["Squashing Commits"][guide-squash])_
- [ ] commits follow the [Conventional ChangeLog][conventional-changelog] format
- [ ] no sensitive content included, such as:
  - content considered competitive intelligence
  - security & privacy policy violating content
  - keys, tokens or credentials

[template]: https://github.com/telus/reference-architecture/blob/master/.template.md
[conventional-changelog]: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular
[guide-squash]: https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History
[technology-forum]: https://github.com/telus/technology-forum]

### CODE REVIEW

**Comment by ahmadnassri** [comment]
please don't link to external resources and bring them inline instead into their own topics

**Comment by owestinTelus** [comment]
Those will be next steps. For now we can link to our existing standards.

*Oskar Westin *

Digital Accessibility Strategy Manager | 647-993-0054
Technical Operations | TELUS digital

**Comment by ruxandrafed** [comment]
Hi @owestinTelus! Do you mind having a look at these linting issues and fixing them? https://circleci.com/gh/telus/reference-architecture/207 (replace the star with dashes as instructed). Thank you!

**Comment by ahmadnassri** [comment]
Oskar, please bring in the individual topics first.

make a PR to each one individually.

we don't want to link to external

**Pull request closed without merging**
